#!/bin/bash
# Graphite uninstall script for Ubuntu 14.04 x64
# Jason Dixon <jason@dixongroup.net>

systemctl stop 'carbon-cache@1' # TODO: more instances need to be stopped
service memcached stop
service collectd stop
service apache2 stop
service statsite stop

# Remove various binaries, configuration files, and source directories
rm /usr/local/sbin/statsite*
rm /etc/statsite.conf
pip3 uninstall -y -r /usr/local/src/graphite-web/requirements.txt
pip3 uninstall -y -r /usr/local/src/carbon/requirements.txt
rm -r /opt/graphite
rm -r /usr/local/src/graphite-web
rm -r /usr/local/src/carbon
rm -r /usr/local/src/whisper
rm -r /usr/local/src/statsite
rm /usr/local/bin/*whisper*.py
rm /usr/local/lib/python2.7/dist-packages/whisper*
rm /etc/apache2/sites-*/graphite.conf
/usr/local/bin/carbon-cache disable
systemctl disable statsite
systemctl disable grafana-server
rm -rf /etc/systemd/system/carbon*
rm -rf /etc/systemd/system/statsite*
systemctl daemon-reload
rm /etc/cron.hourly/graphite-build-index

# Uninstall our package dependencies and purge configurations
apt-get purge -y git wget curl netbase collectd memcached \
           build-essential automake libtool libffi-dev libcairo2-dev libcairo2 libffi6 \
           python3-dev python3-pip fontconfig apache2 libapache2-mod-wsgi-py3
apt-get autoremove -y

# Brute force cleanup on the collectd configuration directory
rm -r /etc/collectd

# Remove our system user for Carbon
pkill -9 -f carbon-cache
userdel carbon
rm /usr/local/bin/carbon-cache