{
 "title": "Graphite Carbon Metrics (obfuscurity)",
 "description": "Obfuscurity's \"extended remix\" of the Graphite Carbon Metrics dashboard",
 "tags": [
  "graphite",
  "carbon"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Carbon Cache Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(sumSeries(carbon.agents.*.updateOperations), 1), 'Updates')"
    },
    {
     "target": "alias(scaleToSeconds(sumSeries(carbon.agents.*.metricsReceived), 1), 'Metrics Received')"
    },
    {
     "target": "alias(scaleToSeconds(sumSeries(carbon.agents.*.committedPoints), 1), 'Committed Points')"
    },
    {
     "target": "alias(averageSeries(carbon.agents.*.pointsPerUpdate), 'Points Per Update')"
    },
    {
     "target": "alias(averageSeries(carbon.agents.*.cpuUsage),'CPU')"
    },
    {
     "target": "alias(scaleToSeconds(sumSeries(carbon.agents.*.creates), 1), 'Creates')"
    }
   ]
  },
  {
   "title": "Carbon Memory & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.memUsage), 'cache memory')"
    },
    {
     "target": "alias(sumSeries(carbon.relays.*.memUsage), 'relay memory')"
    },
    {
     "target": "alias(averageSeries(carbon.agents.*.cpuUsage), 'cache cpu')"
    },
    {
     "target": "alias(averageSeries(carbon.relays.*.cpuUsage), 'relay cpu')"
    }
   ]
  },
  {
   "title": "Number of Metric keys (names) in Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.*.cache.queues, 2)"
    }
   ]
  },
  {
   "title": "Total Datapoints in Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.*.cache.size, 2)"
    }
   ]
  },
  {
   "title": "Relay Destination Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.relays.*.destinations.*.relayMaxQueueLength, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Average datapoints per key in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(averageSeries(carbon.agents.*.cache.size), averageSeries(carbon.agents.*.cache.queues)),\"avg datapoints\")"
    }
   ]
  },
  {
   "title": "Datapoints received during full cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.*.cache.overflow, 2)"
    }
   ]
  },
  {
   "title": "Average Relay Batch Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(#A,#B),\"Relay Batch Size\")"
    }
   ]
  },
  {
   "title": "Disk write ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(collectd.graphite.disk-*.disk_ops.write, 'disk-(\\w+)', '\\1'), 2)"
    }
   ]
  },
  {
   "title": "Disk write time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(collectd.graphite.disk-*.disk_time.write, 'disk-(\\w+)', '\\1'), 2)"
    }
   ]
  },
  {
   "title": "Metric retrieval time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(collectd.graphite.tail-graphite_web.response_time-retrieval_time_min, 100), 3)"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(collectd.graphite.interface-*.if_octets.*, 1), 4)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.graphite.load.load.*, 4)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(averageSeries(collectd.graphite.cpu-*.cpu-interrupt), 'cpu-(\\w+)', '\\1'), 3)"
    },
    {
     "target": "aliasByNode(aliasSub(averageSeries(collectd.graphite.cpu-*.cpu-softirq), 'cpu-(\\w+)', '\\1'), 3)"
    },
    {
     "target": "aliasByNode(aliasSub(averageSeries(collectd.graphite.cpu-*.cpu-steal), 'cpu-(\\w+)', '\\1'), 3)"
    },
    {
     "target": "aliasByNode(aliasSub(averageSeries(collectd.graphite.cpu-*.cpu-system), 'cpu-(\\w+)', '\\1'), 3)"
    },
    {
     "target": "aliasByNode(aliasSub(averageSeries(collectd.graphite.cpu-*.cpu-user), 'cpu-(\\w+)', '\\1'), 3)"
    },
    {
     "target": "aliasByNode(aliasSub(averageSeries(collectd.graphite.cpu-*.cpu-wait), 'cpu-(\\w+)', '\\1'), 3)"
    }
   ]
  }
 ]
}